### ISSUE TITLE
macOS Sierra 

### ISSUE THREAD

**Issue by seb-taillon** [BITespresso/createinstalliso#1]
Fail !
sudo /path/createinstalliso --isodirectory ~/Desktop/ --applicationpath /Applications/Install\ macOS\ Sierra.app/
password:
/Applications/Install macOS Sierra.app/ contains a broken 'createinstallmedia' command.
Fail!

**Comment by BITespresso** [comment]
I think you ran into a known problem with a newer version of the macOS Sierra Installer, which is broken by Apple. 

Please see: [https://github.com/BITespresso/createinstalliso#user-content-error-message--contains-a-broken-createinstallmedia-command](url)
