### ISSUE TITLE
Updated macOS Sierra installer is in fact fixable

### ISSUE THREAD

**Issue by EricFromCanada** [BITespresso/createinstalliso#4]
> it is not possible to use this newer version of the macOS Sierra installer application.

It's possible to use the updated macOS Sierra installer's `createinstallmedia` after making a simple modification: change the installer's version number back to 12.6.03 by running `sudo plutil -replace CFBundleShortVersionString -string "12.6.03" /Applications/Install\ macOS\ Sierra.app/Contents/Info.plist`. 

More info [at this post](https://ericfromcanada.github.io/output/2020/multi-macos-install-drive-diskmaker.html#sierras-installer-bug).

**Comment by BITespresso** [comment]
Solved in [v1.1.0](https://github.com/BITespresso/createinstalliso/releases/tag/v1.1.0)
