### ISSUE TITLE
Request: Update for macOS 12 and 13

### ISSUE THREAD

**Issue by madsmtm** [BITespresso/createinstalliso#6]
It would be nice if this tool worked on those OS'es ;)

**Comment by BITespresso** [comment]
Thanks for your suggestion. I had also planned to do this. It could be the right time to add the latest macOS versions (Monterey, Ventura and Sonoma).

I plan to add those to the next version of the script.

**Comment by BITespresso** [comment]
Solved in [v1.1.0](https://github.com/BITespresso/createinstalliso/releases/tag/v1.1.0)
