### ISSUE TITLE
General question

### ISSUE THREAD

**Issue by brannos** [BITespresso/createinstalliso#8]
Hi - I am trying to run old Mac software liked Flight Simulator. I volunteer at an eWaste and see old software that used to run under Windows 95. Is it worth the effort with Virtual machines or docker as seem to hit roadblocks everywhere?

Maybe just buy some current software?

**Comment by BITespresso** [comment]
It very much depends on the type of VM you are using. For gaming, I would look for a Hackintosh-based solution or a real Mac rather than a simple VMware Workstation on a PC. Otherwise you won't get the graphics acceleration you need.

**Comment by BITespresso** [comment]
It very much depends on the type of VM you are using. For gaming, I would look for a Hackintosh-based solution or a real Mac rather than a simple VMware Workstation on a PC. Otherwise you won't get the graphics acceleration you need.
